In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv(r"C:/Users/OMKAR/Desktop/Practice/archive/movies.csv")
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

#### Data inspection

In [3]:
df.size

89991

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    9999 non-null   object
 1   YEAR      9355 non-null   object
 2   GENRE     9919 non-null   object
 3   RATING    8179 non-null   float64
 4   ONE-LINE  9999 non-null   object
 5   STARS     9999 non-null   object
 6   VOTES     8179 non-null   object
 7   RunTime   7041 non-null   float64
 8   Gross     460 non-null    object
dtypes: float64(2), object(7)
memory usage: 703.2+ KB

In [5]:
df.shape

(9999, 9)

In [6]:
df.dtypes

MOVIES       object
YEAR         object
GENRE        object
RATING      float64
ONE-LINE     object
STARS        object
VOTES        object
RunTime     float64
Gross        object
dtype: object

In [7]:
df.isnull().sum()

MOVIES         0
YEAR         644
GENRE         80
RATING      1820
ONE-LINE       0
STARS          0
VOTES       1820
RunTime     2958
Gross       9539
dtype: int64

### Data Cleaning

#### Changing Column names

In [8]:
df.columns

Index(['MOVIES', 'YEAR', 'GENRE', 'RATING', 'ONE-LINE', 'STARS', 'VOTES',
       'RunTime', 'Gross'],
      dtype='object')

In [9]:
new_col  = {
    'MOVIES' : 'Movies',
    'YEAR' : 'Year',
    'GENRE' : 'Genre',
    'RATING' : 'Rating',
    'ONE-LINE' : 'One-line',
    'STARS' : 'Stars',
    'VOTES' : 'Votes',
}
df.rename(columns = new_col, inplace = True)

In [10]:
df.columns

Index(['Movies', 'Year', 'Genre', 'Rating', 'One-line', 'Stars', 'Votes',
       'RunTime', 'Gross'],
      dtype='object')

In [11]:
df.head()

,Movies,Year,Genre,Rating,One-line,Stars,Votes,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

#### Checking Gross column

In [12]:
not_null_gross = df[df['Gross'].notna()]
not_null_gross

,Movies,Year,Genre,Rating,One-line,Stars,Votes,RunTime,Gross
77,The Hitman's Bodyguard,(2017),"\nAction, Comedy, Crime",6.9,"\nThe world's top bodyguard gets a new client,...",\n Director:\nPatrick Hughes\n| \n Stars...,"205,979",118.0,$75.47M
85,Jurassic Park,(1993),"\nAction, Adventure, Sci-Fi",8.1,\nA pragmatic paleontologist visiting an almos...,\n Director:\nSteven Spielberg\n| \n Sta...,"897,444",127.0,$402.45M
95,Don't Breathe,(2016),"\nCrime, Horror, Thriller",7.1,"\nHoping to walk away with a massive fortune, ...",\n Director:\nFede Alvarez\n| \n Stars:\...,"237,601",88.0,$89.22M
111,The Lord of the Rings: The Fellowship of the Ring,(2001),"\nAction, Adventure, Drama",8.8,\nA meek Hobbit from the Shire and eight compa...,\n Director:\nPeter Jackson\n| \n Stars:...,"1,713,028",178.0,$315.54M
125,Escape Room,(I) (2019),"\nAction, Adventure, Horror",6.4,\nSix strangers find themselves in a maze of d...,\n Director:\nAdam Robitel\n| \n Stars:\...,"99,351",99.0,$57.01M
...,...,...,...,...,...,...,...,...,...
5750,Vidal Sassoon: The Movie,(2010),\nDocumentary,6.5,\nVidal Sassoon is more than just a hairdresse...,\n Director:\nCraig Teper\n| \n Stars:\n...,245,90.0,$0.09M
5770,Men at Lunch,(2012),"\nDocumentary, Mystery",6.3,"\nThe story of ""Lunch atop a Skyscraper,"" the ...",\n Director:\nSeán Ó Cualáin\n| \n Stars...,331,75.0,$0.00M
5835,Decoding Deepak,(2012),\nDocumentary,5.5,"\nDeepak Chopra's son, Gotham, spends a year t...",\n Director:\nGotham Chopra\n| \n Stars:...,124,83.0,$0.01M
6056,Theo Who Lived,(2016),\nDocumentary,6.8,\nA documentary on American journalist Theo Pa...,\n Director:\nDavid Schisgall\n| \n Star...,111,86.0,$0.01M
6292,Southern Justice,(2006),"\nAction, Adventure, Thriller",3.1,"\nM.D. Selig's feature thriller, SOUTHERN JUST...",\n Director:\nM.D. Selig\n| \n Stars:\nM...,126,96.0,$0.14M

#### Cleaning Year column

In [13]:
df[df['Year'].isna()]

,Movies,Year,Genre,Rating,One-line,Stars,Votes,RunTime,Gross
878,Vikings: Valhalla,NaN,"\nAction, Adventure, Drama",NaN,\nFollow-up series to 'Vikings' set 100 years ...,"\n \n Stars:\nLaura Berlin, \nSa...",NaN,NaN,NaN
1375,Resident Evil,NaN,"\nAction, Horror, Sci-Fi",NaN,\nNearly three decades after the discovery of ...,"\n \n Stars:\nLance Reddick, \nS...",NaN,NaN,NaN
1414,Bright 2,NaN,"\nAction, Adventure, Crime",NaN,\nPlot unknown. Sequel to the 2017 film 'Bright.',"\n \n Stars:\nWill Smith, \nJoel...",NaN,NaN,NaN
1419,Avatar: The Last Airbender,NaN,"\nAction, Adventure, Fantasy",NaN,\nLive-action adaptation of the animated serie...,\n,NaN,NaN,NaN
1425,Home Team,NaN,"\nComedy, Sport",NaN,\nThe story about New Orleans Saints head coac...,"\n Directors:\nCharles Francis Kinnane, \nD...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9909,Pretty Smart,NaN,\nComedy,NaN,\nAdd a Plot\n,"\n \n Stars:\nCinthya Carmona, \...",NaN,NaN,NaN
9910,Pretty Smart,NaN,\nComedy,NaN,\nAdd a Plot\n,\n Director:\nJody Margolin Hahn\n| \n S...,NaN,NaN,NaN
9911,Pretty Smart,NaN,\nComedy,NaN,\nAdd a Plot\n,\n Director:\nJody Margolin Hahn\n| \n S...,NaN,NaN,NaN
9912,Pretty Smart,NaN,\nComedy,NaN,\nAdd a Plot\n,"\n \n Stars:\nCinthya Carmona, \...",NaN,NaN,NaN
9913,Pretty Smart,NaN,\nComedy,NaN,\nAdd a Plot\n,"\n \n Stars:\nCinthya Carmona, \...",NaN,NaN,NaN

##### Removing ()

In [14]:
df['Year'].unique()

array(['(2021)', '(2021– )', '(2010–2022)', '(2013– )', '(2020– )',
       '(2006–2013)', '(2019– )', '(2016–2021)', '(2011– )', '(2005– )',
       '(2008–2013)', '(2017– )', '(2017–2021)', '(2016– )',
       '(1994–2004)', '(2014– )', '(2013–2020)', '(2015– )',
       '(2005–2020)', '(2013–2022)', '(2003– )', '(2009–2020)',
       '(I) (2018– )', '(2010–2015)', '(2011–2019)', '(2015–2020)',
       '(2005–2014)', '(2009–2015)', '(2008–2014)', '(2016–2018)',
       '(2009–2017)', '(2020)', '(2018–2021)', '(2017–2020)',
       '(1987–1994)', '(2018– )', '(2012– )', '(2014–2020)',
       '(2011–2018)', '(2005–2017)', '(2017)', '(2007–2015)',
       '(2000–2007)', '(II) (2007– )', '(1993)', '(1999–2022)',
       '(2015–2018)', '(2014–2019)', '(2016)', '(2012–2020)',
       '(2013–2019)', '(2007–2012)', '(2011–2020)', '(2010–2017)',
       '(2000–2015)', '(2015–2021)', '(2001)', '(1997– )', '(2011–2017)',
       '(1993–1999)', '(1989–1998)', '(2010–2013)', '(2010–2020)',
       '(2003–2019)', '(I) (2019)', '(2017–2019)', '(1975)',
       '(2005–2008)', '(1995–2001)', '(2006)', '(2015–2017)',
       '(2008–2020)', '(1984–1996)', '(2010– )', '(2014)', '(2000)',
       '(2013–2018)', '(2009–2016)', '(2016–2020)', '(2021 TV Special)',
       '(2003)', '(1998–2003)', '(I) (2017)', '(1966–1969)', '(2009– )',
       '(2019)', '(1990–1991)', '(2012)', '(1995)', '(2020–2021)',
       '(2013–2017)', '(2015)', '(2019–2020)', '(2017–2018)',
       '(2013–2015)', '(2012–2017)', '(I) (2013–2016)', '(2002)',
       '(I) (2020)', '(III) (2021)', '(2018)', '(II) (2016)', '(1976)',
       '(1978)', '(2016–2019)', '(2009–2014)', '(2022)', '(2011–2014)',
       '(2007–2013)', '(2006–2007)', '(2002–2007)', '(2014–2017)',
       '(2010–2019)', '(2008– )', '(2012–2019)', '(2014–2016)',
       '(2009–2012)', '(2018–2020)', '(2001–2005)', '(2011–2015)',
       '(2014–2018)', '(2015–2019)', '(1982–1993)', '(1998– )', '(1968)',
       '(2010–2018)', '(2014–2021)', '(2007–2010)', '(2011)',
       '(2013–2021)', '(1990–1996)', '(2004)', '(2007–2014)',
       '(1996–2001)', '(2013)', '(2008)', '(1999–2000)', '(2012–2014)',
       '(I) (2013)', '(2012–2018)', '(2018–2019)', '(2009–2013)',
       '(1971)', '(2004– )', '(1989)', '(1998)', '(2001–2018)',
       '(1987–1995)', '(I) (2014)', '(1998–2020)', '(I) (2015)', '(1997)',
       '(2004–2013)', '(2002– )', '(2010)', '(I) (2016)', '(II) (2017– )',
       '(I) (2018)', '(I) (2021)', '(2004–2012)', '(2019–2021)',
       '(IV) (2020)', '(2006–2010)', '(2006–2012)', '(1996)',
       '(1994–2000)', '(II) (2020)', '(1980)', '(I) (2011)',
       '(1995–1996)', '(2016–2017)', '(1993–1996)', '(II) (2019– )',
       '(2009)', '(1962)', '(1991)', '(2022– )', '(II) (2017)',
       '(I) (2012)', '(1984)', '(2011–2016)', '(2009–2019)',
       '(II) (2020– )', '(2006–2021)', '(I) (2010)', '(2012–2015)',
       '(I) (2013–2014)', '(1960)', '(1988)', '(2007)', '(1987)',
       '(2010–2011)', '(1969)', '(2006–2011)', '(II) (2019)', '(1961)',
       '(1979)', '(II) (2022)', '(2014–2015)', '(1956)', '(2013–2016)',
       '(III) (2018)', '(2005)', '(II) (2012– )', '(II) (2013)', '(1983)',
       '(2002–2019)', '(2013 TV Movie)', '(II) (2015)', '(I) (2012–2015)',
       '(1975–1979)', '(1990)', nan, '(II) (2018)', '(IV) (2021)',
       '(2015–2016)', '(1995–1998)', '(1986)', '(2012–2013)', '(1966)',
       '(2011–2012)', '(2011–2021)', '(2016 Video)', '(2017 TV Movie)',
       '(2009–2011)', '(2004–2018)', '(1967)', '(1984– )', '(1994)',
       '(2003–2006)', '(III) (2015)', '(1974)', '(2000–2004)',
       '(1984–2021)', '(I)', '(II) (2021)', '(1994–1999)', '(III)',
       '(1992)', '(1969–1974)', '(2012–2016)', '(2013–2014)',
       '(I) (2008)', '(1958)', '(2008–2009)', '(II) (2004)',
       '(III) (2019)', '(2006–2009)', '(2011–2013)', '(2007–2008)',
       '(1988–1999)', '(2010–2012)', '(2010–2014)', '(II) (2012)',
       '(1932)', '(2014 TV Movie)', '(1941)', '(2006– )', '(1992–1995)',
       '(2016 TV Special)', '(2020 TV Movie)', '(2008–2010)', '(II)',
       '(2020 Video)', '(1999– )', '(1950)', '(2020 TV Special)',
       '(1992–2014)', '(2002–2005)', '(2013 TV Special)', '(I) (2021– )',
       '(1999)', '(2016 TV Movie)', '(XII)', '(VII)', '(2021 TV Movie)',
       '(1983– )', '(1996 Video)', '(1993 TV Movie)', '(2018 TV Movie)',
       '(2005–2009)', '(2001–2002)', '(2015 TV Movie)', '(I) (2020– )',
       '(2011 Video)', '(2008 Video)', '(2012 Video)', '(1946)',
       '(II) (2014)', '(2019 Video)', '(1981–1989)', '(IV) (2016)',
       '(III) (2016)', '(2019 TV Movie)', '(1952)', '(2007 Video)',
       '(2000–2014)', '(1992– )', '(1957)', '(2003–2007)', '(IV)',
       '(2008–2017)', '(2008–2019)', '(1998–2000)', '(I) (2004)',
       '(2007–2016)', '(2017 TV Special)', '(2009 TV Movie)',
       '(2013 Video)', '(2017 Video)', '(1994–1996)', '(IV) (2017)',
       '(IV) (2018)', '(2007– )', '(1954)', '(2012 TV Movie)', '(1995– )',
       '(1982)', '(1955)', '(2014 TV Short)', '(I) (2022– )',
       '(I) (2019–2020)', '(1975 TV Movie)', '(2019 TV Special)',
       '(2015 TV Special)', '(2015 TV Short)', '(2018 TV Special)',
       '(1948)', '(2014 Video)', '(VI) (2014)', '(2003–2013)',
       '(2021 Video)', '(1947)', '(2001– )', '(II) (2021– )',
       '(1997–2000)', '(III) (2020)', '(I) (2019– )', '(1993– )',
       '(1977)', '(I) (2009)', '(V)', '(2023)', '(I) (2000)',
       '(TV Special)', '(II) (2011)', '(TV Movie)', '(1945)',
       '(2015 Video)', '(III) (2010)', '(2009 Video)', '(1998–2002)',
       '(2008 TV Movie)', '(2019 TV Short)', '(2004 Video)',
       '(II) (1998)', '(2014 TV Special)', '(1953)', '(1985)', '(VIII)',
       '(1973)', '(2012 TV Special)', '(V) (2016)', '(1972)',
       '(V) (2018)', '(II) (2010)', '(2021 TV Short)', '(VI) (2019)',
       '(I) (2005)', '(1965)', '(2010–2016)', '(V) (2010)', '(2005–2013)',
       '(2006 TV Special)', '(2006 Video)', '(2011 TV Movie)',
       '(1988 TV Movie)', '(XXIII)', '(2011 TV Special)',
       '(2020 TV Short)', '(VI) (2018)', '(2008 TV Special)',
       '(1998–1999)', '(I) (2015– )', '(III) (2012)', '(VI)',
       '(2010 TV Special)', '(III) (2017)', '(1993 TV Special)',
       '(2004–2005)', '(1992 Video)', '(1989 TV Special)', '(XI)',
       '(III) (2014)', '(1966 TV Special)', '(1999 TV Movie)',
       '(1987 TV Special)', '(1944)', '(1998 TV Special)',
       '(2006 TV Movie)', '(2022 TV Special)', '(1989 Video)',
       '(1991 TV Special)', '(XLI)', '(IV) (2014)', '(2005 Video)',
       '(2007 TV Special)', '(1965 TV Special)', '(1990 TV Special)',
       '(2001 TV Special)', '(IX)', '(II) (2016– )', '(XIV) (2017)',
       '(2009–2010)', '(XIII)', '(II) (2012–2019)', '(1933)',
       '(II) (2009)', '(2010 Video)', '(2009 TV Special)', '(1938)',
       '(2003 TV Special)', '(Video)', '(2001 TV Movie)', '(VI) (2016)',
       '(III) (2011)', '(2007 TV Movie)', '(2017 TV Short)',
       '(2018 Video)', '(2000 Video)', '(1995 Video)', '(2003 Video)',
       '(II) (2016 TV Movie)', '(1998 Video)', '(2005 TV Special)',
       '(2004–2009)', '(2018 Video Game)', '(1988– )', '(1985– )'],
      dtype=object)

In [15]:
df['Year'] = df['Year'].str.replace(r'\W', '', regex = True)
df['Year'].head()

0        2021
1        2021
2    20102022
3        2013
4        2021
Name: Year, dtype: object

In [16]:
df.head()

,Movies,Year,Genre,Rating,One-line,Stars,Votes,RunTime,Gross
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,20102022,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,2013,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

In [17]:
df['Year'].unique()

array(['2021', '20102022', '2013', '2020', '20062013', '2019', '20162021',
       '2011', '2005', '20082013', '2017', '20172021', '2016', '19942004',
       '2014', '20132020', '2015', '20052020', '20132022', '2003',
       '20092020', 'I2018', '20102015', '20112019', '20152020',
       '20052014', '20092015', '20082014', '20162018', '20092017',
       '20182021', '20172020', '19871994', '2018', '2012', '20142020',
       '20112018', '20052017', '20072015', '20002007', 'II2007', '1993',
       '19992022', '20152018', '20142019', '20122020', '20132019',
       '20072012', '20112020', '20102017', '20002015', '20152021', '2001',
       '1997', '20112017', '19931999', '19891998', '20102013', '20102020',
       '20032019', 'I2019', '20172019', '1975', '20052008', '19952001',
       '2006', '20152017', '20082020', '19841996', '2010', '2000',
       '20132018', '20092016', '20162020', '2021TVSpecial', '19982003',
       'I2017', '19661969', '2009', '19901991', '1995', '20202021',
       '20132017', '20192020', '20172018', '20132015', '20122017',
       'I20132016', '2002', 'I2020', 'III2021', 'II2016', '1976', '1978',
       '20162019', '20092014', '2022', '20112014', '20072013', '20062007',
       '20022007', '20142017', '20102019', '2008', '20122019', '20142016',
       '20092012', '20182020', '20012005', '20112015', '20142018',
       '20152019', '19821993', '1998', '1968', '20102018', '20142021',
       '20072010', '20132021', '19901996', '2004', '20072014', '19962001',
       '19992000', '20122014', 'I2013', '20122018', '20182019',
       '20092013', '1971', '1989', '20012018', '19871995', 'I2014',
       '19982020', 'I2015', '20042013', 'I2016', 'II2017', 'I2021',
       '20042012', '20192021', 'IV2020', '20062010', '20062012', '1996',
       '19942000', 'II2020', '1980', 'I2011', '19951996', '20162017',
       '19931996', 'II2019', '1962', '1991', 'I2012', '1984', '20112016',
       '20092019', '20062021', 'I2010', '20122015', 'I20132014', '1960',
       '1988', '2007', '1987', '20102011', '1969', '20062011', '1961',
       '1979', 'II2022', '20142015', '1956', '20132016', 'III2018',
       'II2012', 'II2013', '1983', '20022019', '2013TVMovie', 'II2015',
       'I20122015', '19751979', '1990', nan, 'II2018', 'IV2021',
       '20152016', '19951998', '1986', '20122013', '1966', '20112012',
       '20112021', '2016Video', '2017TVMovie', '20092011', '20042018',
       '1967', '1994', '20032006', 'III2015', '1974', '20002004',
       '19842021', 'I', 'II2021', '19941999', 'III', '1992', '19691974',
       '20122016', '20132014', 'I2008', '1958', '20082009', 'II2004',
       'III2019', '20062009', '20112013', '20072008', '19881999',
       '20102012', '20102014', '1932', '2014TVMovie', '1941', '19921995',
       '2016TVSpecial', '2020TVMovie', '20082010', 'II', '2020Video',
       '1999', '1950', '2020TVSpecial', '19922014', '20022005',
       '2013TVSpecial', '2016TVMovie', 'XII', 'VII', '2021TVMovie',
       '1996Video', '1993TVMovie', '2018TVMovie', '20052009', '20012002',
       '2015TVMovie', '2011Video', '2008Video', '2012Video', '1946',
       'II2014', '2019Video', '19811989', 'IV2016', 'III2016',
       '2019TVMovie', '1952', '2007Video', '20002014', '1957', '20032007',
       'IV', '20082017', '20082019', '19982000', 'I2004', '20072016',
       '2017TVSpecial', '2009TVMovie', '2013Video', '2017Video',
       '19941996', 'IV2017', 'IV2018', '1954', '2012TVMovie', '1982',
       '1955', '2014TVShort', 'I2022', 'I20192020', '1975TVMovie',
       '2019TVSpecial', '2015TVSpecial', '2015TVShort', '2018TVSpecial',
       '1948', '2014Video', 'VI2014', '20032013', '2021Video', '1947',
       '19972000', 'III2020', '1977', 'I2009', 'V', '2023', 'I2000',
       'TVSpecial', 'II2011', 'TVMovie', '1945', '2015Video', 'III2010',
       '2009Video', '19982002', '2008TVMovie', '2019TVShort', '2004Video',
       'II1998', '2014TVSpecial', '1953', '1985', 'VIII', '1973',
       '2012TVSpecial', 'V2016', '1972', 'V2018', 'II2010', '2021TVShort',
       'VI2019', 'I2005', '1965', '20102016', 'V2010', '20052013',
       '2006TVSpecial', '2006Video', '2011TVMovie', '1988TVMovie',
       'XXIII', '2011TVSpecial', '2020TVShort', 'VI2018', '2008TVSpecial',
       '19981999', 'III2012', 'VI', '2010TVSpecial', 'III2017',
       '1993TVSpecial', '20042005', '1992Video', '1989TVSpecial', 'XI',
       'III2014', '1966TVSpecial', '1999TVMovie', '1987TVSpecial', '1944',
       '1998TVSpecial', '2006TVMovie', '2022TVSpecial', '1989Video',
       '1991TVSpecial', 'XLI', 'IV2014', '2005Video', '2007TVSpecial',
       '1965TVSpecial', '1990TVSpecial', '2001TVSpecial', 'IX', 'XIV2017',
       '20092010', 'XIII', 'II20122019', '1933', 'II2009', '2010Video',
       '2009TVSpecial', '1938', '2003TVSpecial', 'Video', '2001TVMovie',
       'VI2016', 'III2011', '2007TVMovie', '2017TVShort', '2018Video',
       '2000Video', '1995Video', '2003Video', 'II2016TVMovie',
       '1998Video', '2005TVSpecial', '20042009', '2018VideoGame'],
      dtype=object)

In [18]:
df['Year'] = df['Year'].replace('[a-z[A-Z]', '', regex = True)

In [19]:
 df['Year'].unique()

array(['2021', '20102022', '2013', '2020', '20062013', '2019', '20162021',
       '2011', '2005', '20082013', '2017', '20172021', '2016', '19942004',
       '2014', '20132020', '2015', '20052020', '20132022', '2003',
       '20092020', '2018', '20102015', '20112019', '20152020', '20052014',
       '20092015', '20082014', '20162018', '20092017', '20182021',
       '20172020', '19871994', '2012', '20142020', '20112018', '20052017',
       '20072015', '20002007', '2007', '1993', '19992022', '20152018',
       '20142019', '20122020', '20132019', '20072012', '20112020',
       '20102017', '20002015', '20152021', '2001', '1997', '20112017',
       '19931999', '19891998', '20102013', '20102020', '20032019',
       '20172019', '1975', '20052008', '19952001', '2006', '20152017',
       '20082020', '19841996', '2010', '2000', '20132018', '20092016',
       '20162020', '19982003', '19661969', '2009', '19901991', '1995',
       '20202021', '20132017', '20192020', '20172018', '20132015',
       '20122017', '20132016', '2002', '1976', '1978', '20162019',
       '20092014', '2022', '20112014', '20072013', '20062007', '20022007',
       '20142017', '20102019', '2008', '20122019', '20142016', '20092012',
       '20182020', '20012005', '20112015', '20142018', '20152019',
       '19821993', '1998', '1968', '20102018', '20142021', '20072010',
       '20132021', '19901996', '2004', '20072014', '19962001', '19992000',
       '20122014', '20122018', '20182019', '20092013', '1971', '1989',
       '20012018', '19871995', '19982020', '20042013', '20042012',
       '20192021', '20062010', '20062012', '1996', '19942000', '1980',
       '19951996', '20162017', '19931996', '1962', '1991', '1984',
       '20112016', '20092019', '20062021', '20122015', '20132014', '1960',
       '1988', '1987', '20102011', '1969', '20062011', '1961', '1979',
       '20142015', '1956', '1983', '20022019', '19751979', '1990', nan,
       '20152016', '19951998', '1986', '20122013', '1966', '20112012',
       '20112021', '20092011', '20042018', '1967', '1994', '20032006',
       '1974', '20002004', '19842021', '', '19941999', '1992', '19691974',
       '20122016', '1958', '20082009', '20062009', '20112013', '20072008',
       '19881999', '20102012', '20102014', '1932', '1941', '19921995',
       '20082010', '1999', '1950', '19922014', '20022005', '20052009',
       '20012002', '1946', '19811989', '1952', '20002014', '1957',
       '20032007', '20082017', '20082019', '19982000', '20072016',
       '19941996', '1954', '1982', '1955', '1948', '20032013', '1947',
       '19972000', '1977', '2023', '1945', '19982002', '1953', '1985',
       '1973', '1972', '1965', '20102016', '20052013', '19981999',
       '20042005', '1944', '20092010', '1933', '1938', '20042009'],
      dtype=object)

In [20]:
df['Year'].isnull().sum()

644

In [24]:
df['Year'] = df['Year'].astype(str).apply(lambda x: x[4:] if len(x) > 4 else x)
print(df)

                                   Movies  Year  \
0                           Blood Red Sky  2021
1     Masters of the Universe: Revelation  2021
2                        The Walking Dead  2022
3                          Rick and Morty  2013
4                         Army of Thieves  2021
...                                   ...   ...
9994                       The Imperfects  2021
9995                               Arcane  2021
9996                    Heart of Invictus  2022
9997                       The Imperfects  2021
9998                       The Imperfects  2021

                                           Genre  Rating  \
0         \nAction, Horror, Thriller                 6.1
1     \nAnimation, Action, Adventure                 5.0
2          \nDrama, Horror, Thriller                 8.2
3     \nAnimation, Adventure, Comedy                 9.2
4            \nAction, Crime, Horror                 NaN
...                                          ...     ...
9994     \nAdventure, Drama, Fantasy                 NaN
9995  \nAnimation, Action, Adventure                 NaN
9996            \nDocumentary, Sport                 NaN
9997     \nAdventure, Drama, Fantasy                 NaN
9998     \nAdventure, Drama, Fantasy                 NaN

                                               One-line  \
0     \nA woman with a mysterious illness is forced ...
1     \nThe war for Eternia begins again in what may...
2     \nSheriff Deputy Rick Grimes wakes up from a c...
3     \nAn animated series that follows the exploits...
4     \nA prequel, set before the events of Army of ...
...                                                 ...
9994                                     \nAdd a Plot\n
9995                                     \nAdd a Plot\n
9996                                     \nAdd a Plot\n
9997                                     \nAdd a Plot\n
9998                                     \nAdd a Plot\n

                                                  Stars    Votes  RunTime  \
0     \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062    121.0
1     \n            \n    Stars:\nChris Wood, \nSara...   17,870     25.0
2     \n            \n    Stars:\nAndrew Lincoln, \n...  885,805     44.0
3     \n            \n    Stars:\nJustin Roiland, \n...  414,849     23.0
4     \n    Director:\nMatthias Schweighöfer\n| \n  ...      NaN      NaN
...                                                 ...      ...      ...
9994  \n            \n    Stars:\nMorgan Taylor Camp...      NaN      NaN
9995                                                 \n      NaN      NaN
9996  \n    Director:\nOrlando von Einsiedel\n| \n  ...      NaN      NaN
9997  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      NaN
9998  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      NaN

     Gross
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
...    ...
9994   NaN
9995   NaN
9996   NaN
9997   NaN
9998   NaN

[9999 rows x 9 columns]

In [26]:
df['Year'].unique()

array(['2021', '2022', '2013', '2020', '2019', '2011', '2005', '2017',
       '2016', '2004', '2014', '2015', '2003', '2018', '1994', '2012',
       '2007', '1993', '2001', '1997', '1999', '1998', '1975', '2008',
       '2006', '1996', '2010', '2000', '1969', '2009', '1991', '1995',
       '2002', '1976', '1978', '1968', '1971', '1989', '1980', '1962',
       '1984', '1960', '1988', '1987', '1961', '1979', '1956', '1983',
       '1990', 'nan', '1986', '1966', '1967', '1974', '', '1992', '1958',
       '1932', '1941', '1950', '1946', '1952', '1957', '1954', '1982',
       '1955', '1948', '1947', '1977', '2023', '1945', '1953', '1985',
       '1973', '1972', '1965', '1944', '1933', '1938'], dtype=object)

In [27]:
df

,Movies,Year,Genre,Rating,One-line,Stars,Votes,RunTime,Gross
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,2022,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,2013,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,2021,"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,2021,"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,2022,"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,2021,"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,2021,"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

#### Genre Column

In [28]:
df['Genre'].head()

0        \nAction, Horror, Thriller
1    \nAnimation, Action, Adventure
2         \nDrama, Horror, Thriller
3    \nAnimation, Adventure, Comedy
4           \nAction, Crime, Horror
Name: Genre, dtype: object

In [30]:
df['Genre'] = df['Genre'].str.replace(r'\n', '', regex = True)
df['Genre']

0           Action, Horror, Thriller
1       Animation, Action, Adventure
2            Drama, Horror, Thriller
3       Animation, Adventure, Comedy
4              Action, Crime, Horror
                          ...
9994       Adventure, Drama, Fantasy
9995    Animation, Action, Adventure
9996              Documentary, Sport
9997       Adventure, Drama, Fantasy
9998       Adventure, Drama, Fantasy
Name: Genre, Length: 9999, dtype: object

#### Rating Column

In [31]:
df['Rating'].isnull().sum()

1820

In [32]:
df['Rating'].unique()

array([6.1, 5. , 8.2, 9.2, nan, 7.6, 6.8, 8.6, 7.9, 7.4, 6. , 8.1, 6.2,
       5.4, 8. , 7.5, 9.4, 8.3, 8.7, 8.9, 8.8, 8.5, 8.4, 6.7, 7.7, 9. ,
       5.8, 3.3, 7.8, 5.7, 6.6, 6.9, 6.5, 7.1, 5.6, 7.3, 9.1, 7.2, 6.4,
       9.3, 7. , 6.3, 3.7, 5.5, 4.6, 4.8, 5.3, 4.7, 5.9, 5.1, 4.9, 2.7,
       4.4, 3.1, 4.5, 4.2, 3.8, 5.2, 2.8, 3.5, 4.3, 3.2, 1.1, 3.9, 4. ,
       3.4, 2.6, 3.6, 3. , 2.5, 2.2, 2.9, 4.1, 2.1, 2. , 2.3, 2.4, 1.8,
       9.6, 9.5, 9.7, 9.9, 9.8])

In [35]:
df['Rating'] = df['Rating'].astype(str).str.replace('\.0$', '').str.replace('\.$', '')

C:\Users\OMKAR\AppData\Local\Temp/ipykernel_9820/2250064718.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Rating'] = df['Rating'].astype(str).str.replace('\.0$', '').str.replace('\.$', '')

In [36]:
df['Rating'].unique()

array(['6.1', '5', '8.2', '9.2', 'nan', '7.6', '6.8', '8.6', '7.9', '7.4',
       '6', '8.1', '6.2', '5.4', '8', '7.5', '9.4', '8.3', '8.7', '8.9',
       '8.8', '8.5', '8.4', '6.7', '7.7', '9', '5.8', '3.3', '7.8', '5.7',
       '6.6', '6.9', '6.5', '7.1', '5.6', '7.3', '9.1', '7.2', '6.4',
       '9.3', '7', '6.3', '3.7', '5.5', '4.6', '4.8', '5.3', '4.7', '5.9',
       '5.1', '4.9', '2.7', '4.4', '3.1', '4.5', '4.2', '3.8', '5.2',
       '2.8', '3.5', '4.3', '3.2', '1.1', '3.9', '4', '3.4', '2.6', '3.6',
       '3', '2.5', '2.2', '2.9', '4.1', '2.1', '2', '2.3', '2.4', '1.8',
       '9.6', '9.5', '9.7', '9.9', '9.8'], dtype=object)